### ISSUE TITLE
Linter integration ignores "directories" .reek.yml configuration (VSCode)

### ISSUE THREAD

**Issue by thejonroberts** [igray/ruby-lsp-reek#2]
I'm running a rails project and getting editor lint squiggles even though `bundle exec reek` has no smell violations... Am I missing some configuration or are the directories rules not respected?

Using the following `.reek.yml` config (in a rails project):
```yml
---
detectors:
  IrresponsibleModule:
    enabled: false

directories:
  "app/controllers":
    IrresponsibleModule:
      enabled: false
    NestedIterators:
      max_allowed_nesting: 2
    UnusedPrivateMethod:
      enabled: false
    InstanceVariableAssumption:
      enabled: false
    DuplicateMethodCall:
      enabled: false
    TooManyStatements:
      enabled: false
  "app/helpers":
    IrresponsibleModule:
      enabled: false
    UtilityFunction:
      enabled: false
  "app/mailers":
    InstanceVariableAssumption:
      enabled: false
  "app/models":
    InstanceVariableAssumption:
      enabled: false
  "db/migrate":
    FeatureEnvy:
      enabled: false
    TooManyStatements:
      enabled: false
    UncommunicativeVariableName:
      enabled: false
```
Results in warnings in files where they should be disabled: 
<img width="777" alt="Screenshot 2024-11-18 at 4 06 30 PM" src="https://github.com/user-attachments/assets/047f17c1-b99e-4f90-9567-f6efd0a8d93b">

I also tried with glob patterns like `"**/db/migrate"`, with the same results.

I'm running VSCode with the Ruby-LSP extension and the following user settings:
```json
"rubyLsp.enabledFeatures": {
  "codeActions": true,
  "diagnostics": true,
  "documentHighlights": true,
  "documentLink": true,
  "documentSymbols": true,
  "foldingRanges": false,
  "formatting": true,
  "hover": true,
  "inlayHint": true,
  "onTypeFormatting": false,
  "selectionRanges": true,
  "semanticHighlighting": true,
  "completion": true,
  "codeLens": true,
  "definition": true,
  "workspaceSymbol": true,
  "signatureHelp": true,
  "typeHierarchy": true
,
"rubyLsp.enableExperimentalFeatures": false,
"rubyLsp.rubyVersionManager": {
  "identifier": "custom"
},
rubyLsp.customRubyCommand": "eval \"$(frum init)\"",
"rubyLsp.linters": [
  "rubocop",
  "reek",
],
```

NOTE: Possibly a separate issue -- Changing .reek.yml does not update the linting. This error in the vs code Ruby LSP output:
```sh
2024-11-18 14:02:39.397 [info] (rails-8-playground-rspec) Error processing workspace/didChangeWatchedFiles: /Users/jon/.frum/versions/3.3.6/lib/ruby/gems/3.3.0/gems/ruby-lsp-reek-0.2.0/lib/ruby_lsp/reek/addon.rb:71:in `workspace_did_change_watched_files': undefined method `init!' for an instance of RubyLsp::Reek::Runner (NoMethodError)

        runner.init!
              ^^^^^^
	from /Users/jon/.frum/versions/3.3.6/lib/ruby/gems/3.3.0/gems/ruby-lsp-0.21.3/lib/ruby_lsp/server.rb:983:in `block in workspace_did_change_watched_files'
	from /Users/jon/.frum/versions/3.3.6/lib/ruby/gems/3.3.0/gems/ruby-lsp-0.21.3/lib/ruby_lsp/server.rb:983:in `each'
	from /Users/jon/.frum/versions/3.3.6/lib/ruby/gems/3.3.0/gems/ruby-lsp-0.21.3/lib/ruby_lsp/server.rb:983:in `workspace_did_change_watched_files'
	from /Users/jon/.frum/versions/3.3.6/lib/ruby/gems/3.3.0/gems/ruby-lsp-0.21.3/lib/ruby_lsp/server.rb:81:in `process_message'
	from /Users/jon/.frum/versions/3.3.6/lib/ruby/gems/3.3.0/gems/ruby-lsp-0.21.3/lib/ruby_lsp/base_server.rb:163:in `block in new_worker'
```

Restarting the LSP server does not result in an error
